### ISSUE TITLE
Cannot execute the jar file

### ISSUE THREAD

**Issue by afbrogneaux** [cetic/rts-gen-ms#1]
```
$ java -jar rts-generator-ws.jar -h 0.0.0.0 -p 8001

Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: reference.conf @ jar:file:/C:/Users/afb/Documents/Travail/projets/eam-sdi/code/ts-generator-ws-assembly/rts-generator-ws.jar!/reference.conf: 15: Could not resolve substitution to a value: ${akka.version}
        at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:108)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.ConfigConcatenation.resolveSubstitutions(ConfigConcatenation.java:205)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:231)
        at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:74)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:64)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:59)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:37)
        at com.typesafe.config.impl.ConfigImpl$1.call(ConfigImpl.java:374)
        at com.typesafe.config.impl.ConfigImpl$1.call(ConfigImpl.java:367)
        at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:65)
        at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:92)
        at com.typesafe.config.impl.ConfigImpl.defaultReference(ConfigImpl.java:367)
        at com.typesafe.config.ConfigFactory.defaultReference(ConfigFactory.java:413)
        at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:212)
        at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:181)
        at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:305)
        at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:302)
        at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:65)
        at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:92)
        at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:302)
        at akka.actor.ActorSystem$$anonfun$4.apply(ActorSystem.scala:141)
        at akka.actor.ActorSystem$$anonfun$4.apply(ActorSystem.scala:141)
        at scala.Option.getOrElse(Option.scala:121)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
        at be.cetic.rtsgen.genservice.GeneratorWebServer$.main(GeneratorWebServer.scala:47)
        at be.cetic.rtsgen.genservice.GeneratorWebServer.main(GeneratorWebServer.scala)

```

**Comment by mgoeminne** [comment]
This issue is likely to be due to the fact that IntelliJ, which is used to generate the runnable jar file, is not able to correctly resolve some configuration variables.

Packaging with SBT seems to fix it:

> sbt assembly

The release has been updated in order to fix the problem without creating a new release, since the source code remains unchanged.
